// List of words to censor
export const BAD_WORDS: string[] = [
    'dracu',
    'coaie',
    'coit',
    'coaiemiu',
    'dracului',
    'mortii',
    'mortii tai',
    'mă-tii',
    'matii',
    'măta',    
    'mă-ta',  
    'mă-sii',
    'pula',
    'pulă',
    'pizda',
    'pizdă',
    'futu',
    'futut',
    'futui',
    'futu-ti',
    'fututi',
    'futu-i',
    'futu-va',
    'futu-te',
    'fututa',
    'fututo',
    'fututi',
    'cur',
    'curva',
    'curve',
    'curvă',
    'curvă-sa',
    'proasto',
    'prostu',
    'prostule',
    'proasto',
    'proasta',
    'handicapat',
    'handicapato',
    'handicapați',
    'retardat',
    'retardată',
    'idiot',
    'idioată',
    'javră',
    'javra',
    'muie',
    'muiți',
    'muista',
    'muistă',
    'muisto',
    'poponar',
    'poponari',
    'poponarule',
    'jigodie',
    'jigodii',
    'băga-mi as pula',
    'bagami',
    'bagamias',
    'bagami-as',
    'bagamiaspula',
    'bagamias pula',
    'bagamias curu',
    'bagamias dracu',
    'du-te-n pizda mă-tii',
    'du-te-n pula',
    'du-te-n mă-ta',
  ];
  