name: Deactivate Old Projects

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:      # Allow manual trigger

jobs:
  deactivate-projects:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call deactivation endpoint
        run: |
          curl -X GET "${{ secrets.VERCEL_URL }}/api/cron/deactivate-projects" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }} 